### ISSUE TITLE
define function incorrect

### ISSUE THREAD

**Issue by GontemDo** [requirejs/requirejs#1593] opened 2016-10-04 06:45 UTC
```js
define(function(require){
    return {
        a:'/*',
        b:require('b'), // didn't loaded but need
        c:'*/',
        d:"require('d')" // loaded while not needed
    };
});
```

**Comment by jrburke** [comment] 2016-10-05 03:37
This is definitely a weakness in the loader when it tries to parse dependencies at runtime due to it using regexps to strip out comments and find dependencies. A better regexp might be possible, but need to balance it with catching valid cases when comments should be removed. The current regexp has been there for many years now.

The issue is specifically [this part of require.js](https://github.com/requirejs/requirejs/blob/3e55417e118205553240a4a7ad3aac791065713d/require.js#L2082) where it uses commentRegExp to strip out comments.

I will leave this ticket open for a bit in case others have a thought on how commentRegExp might work differently, but given the time it has been there and the constraints of wanting something small and fast for this case (the performance would be much worse shipping a whole JS parser and AST solution in the runtime loader), I expect there will always be edge cases like this that will be a problem.

Mitigations:

1) The r.js optimizer does not have this problem since it uses a JS parser and AST to find dependencies. The optimizer will also write out the dependencies in the define call when it bundles the file to avoid this sort of problem after a build. So you can always do a build with the optimizer first to avoid this possibility.

2) For these known individual cases, you can switch to including the dependencies in the dependency array signature for define, but just be sure to include all dependencies in that case:

```javascript
define(['require', 'b', 'd'], function(require){
    return {
        a:'/*',
        b:require('b'), // didn't loaded but need
        c:'*/',
        d:"require('d')" // loaded while not needed
    };
});
```

**Comment by GontemDo** [comment] 2016-10-10 09:03
@jrburke 
You are right.
I think requirejs should not be changed,
RegExp is not for every case,
cause edge cases could even include:
```js
define(function(require){
    var r=require,
        moduleName=function(){return 'module-name';};
    return r(moduleName);
});
```
Only AST (and need real running) can process this,
which leads to bloated, slow, and cause more runtime problem.
I think the target of designing `require('...')` mode, is for lightweight using.

BTW: Your expedient solution in the end is so tactful. XD

**Comment by jrburke** [comment] 2016-10-10 18:34
Going to close this ticket out for now given the above conversation. If there are people that want to consider the problem more, #1594 might be a good place to do that. But note my comment in that ticket about any change needing to meet a pretty high bar.

**Closed by jrburke** 2016-10-10 18:34 UTC
