### ISSUE TITLE
relative path , text plugin fetch wrong url.

### ISSUE THREAD

**Issue by Hanruis** [requirejs/requirejs#1571] opened 2016-08-09 11:22 UTC
when i use relative path to require the module , and in the module require a  text file ( use text plugin ), the text plugin fetchs a wrong url 

main.js like this
```
require.config({
    baseUrl: '/base/src',
    //..
});

(function() {
    "use strict"
        var deps = [];
        deps.push("../test/spec/baseView/baseView_spec")
        require(deps, function() {
            window.__karma__.start()
        });
})();
```
and then ,in  baseView_spec.js . I require a html file .
` var templates = require("text!./templates.tpl.html");`

and finaly , text plugin fetch the  html file in  wrong url :
`http://hostname/base/test/spec/test/spec/test/spec/baseView/templates.tpl.html`;

I found that it seem that happen in function `normalize` . for `templates.tpl.html`  request, it's parent module's name will awalys be '../test/spec/baseView/baseView_spec' . so that  every time `normalize` the html file request , will return file path will '..' suffix . example :'../test/spec/baseView/templates.tpl.html'

**Comment by jrburke** [comment] 2016-08-10 14:02
It looks like the issue is the "../test/spec/baseView/baseView_spec" ID. Since the starting "../" would be outside of the module ID space, the loader has a hard time then using it for ID resolutions later. Add in a "paths" config for "test" and then use that "test" module ID prefix for the spec module ID:

```javascript
require.config({
    baseUrl: '/base/src',
    paths: {
        // path value is relative to baseUrl.
        test: '../test'
    }
    //..
});

(function() {
    "use strict"
        var deps = [];
        deps.push("test/spec/baseView/baseView_spec")
        require(deps, function() {
            window.__karma__.start()
        });
})();
```

I believe that should fix the issue, so closing this ticket as a discussion ticket. Feel free to continue discussion here though.

**Closed by jrburke** 2016-08-10 14:02 UTC
