### ISSUE TITLE
Why do I have to use the relative paths for two modules but for others not?

### ISSUE THREAD

**Issue by Legends** [requirejs/requirejs#1615] opened 2016-11-27 16:57 UTC
As I can see, there is no circular reference ....

I have to folders: **Scripts** and **Scripts-Built**.

Scripts folder is for the source files. (debug)
Script-Built contains the same files but optimized/concatenated. (release)

CMD:  ` MySiteBaseName> node r.js -o Scripts/app.build.js`

**Release:**
```
    <script src="~/Scripts-built/require.js"></script>
    <script src="~/Scripts-built/config.js"></script>
```

**Debug:**
```
    <script src="~/Scripts/require.js"></script>
    <script src="~/Scripts/config.js"></script>
```

**Config:**
At the end of the config file I do a require(["config"]... in order to have the config loaded on every page.
I don't know if this is the right way???
As you can see I have specified paths for the index.js and about.js.
But when I specify them as an dependency in the View I have to specify the relative path for each of them. But the other dependencies i can define by module id without getting undefined!

Why do I have to specify the relative path instead of simply using the module id for "index or about" ???

```
require.config({

    baseUrl: '/MySiteBaseName/Scripts-Built',
    paths: {
        jquery:
        //    [
        //    '//code.jquery.com/jquery-3.1.1.min',
            'jquery-3.1.1'
        //]
        ,
        bootstrap:
            //[
            //'//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min',
        'bootstrap-3.3.7'
        //],
            ,
        modernizr:
            //[
            //'//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min',
            'modernizr-2.8.3'
        //],
        ,
        html5shiv: 'html5shiv-printshiv-3.7.3',
        respondjs:
            //[
            //'//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min',
            'respond-1.4.2.min'
        //],
        ,
        text: 'text',
        config: 'config',
        index: 'app/main/index',
        about: 'app/main/about',
        aps: 'app/app', 
        //clipboard: 'clipboard',
        lodash:
            //[
            //'//cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.2/lodash.min',
            'lodash.4.17.2.min'
        //],
        ,
        typeahead: 'typeahead.bundle.min',
        backbone: 'backbone',
        underscore: 'underscore',
        json2: 'json2',  
        purchase: 'mods/purchase',
        credits: 'mods/credits',
        products: 'mods/products',
        person: 'mods/person'
    }
  ,
    //"waitSeconds": 0, // script load timeout
    shim: {
        "bootstrap": { "deps": ['jquery'] },
        "config": { "deps": ['jquery'] }
    }
});

require(['config'], function (config) {
    //config is loaded now.
});
```

**Index.cshtml:**
If a set it to only "index" I get undefined in the callback! **Why**?
```
<script>
        requirejs(["app/main/index", "aps", "jquery"], function (index, ap, $$$) { //, "aps", "jquery"

            ap.init();

            var x = 0;
            $$$(document).ready(function () {

                requirejs(["app/main/index"], function (index) {
                    index.say();
                });
            });
        })        
    </script>
```

**Here is the about.js implementation**, which has a dependency on clipboard.js:
```
define(['clipboard'], function (cb) {
   
    return { cb: cb };
});
```

![image](https://cloud.githubusercontent.com/assets/966368/20650486/ce64421e-b4cf-11e6-9882-48ce6d5145af.png)

**Comment by jrburke** [comment] 2016-11-28 05:32
From a brief scan it looks like the issue is that the paths config mentions `index: 'app/main/index', but the requirejs call does `requirejs(['app/main/index', ....`. 

If you set up the paths config like that, then always asks for the module as 'index'. In general you only want to refer to a module by one module ID. By setting up 'index' and 'app/main/index' to point to the same module in that index.js file, then that will cause problems, as the loader can only assign the module export to one of those values, and that would explain why you get an undefined value for one of those references.

If your app needs to use both 'index' and 'app/main/index' to refer to the modules for some reason that you cannot change, then [map config](http://requirejs.org/docs/api.html#config-map) should be used instead of paths config.

Closing as a discussion ticket, but feel free to continue discussion here.

**Closed by jrburke** 2016-11-28 05:32 UTC

**Comment by Legends** [comment] 2016-11-28 14:02
No, it only works when I specify the dependency as a relative path:
This: `requirejs(['index'], ...` does not work.

Ok, I found the issue in my **build file**.

When replacing this:

```
                {
			name: "app/main/index",
			exclude: ["config"]
		},
		{
			name: "app/main/about",
			exclude: ["config"]
		}
```
with this:

```
                {
			name: "index",
			exclude: ["config"]
		},
		{
			name: "about",
			exclude: ["config"]
		}
```

So "Name" has to be the module id!
