### ISSUE TITLE
the meaning of `module` in the context of a require() callback

### ISSUE THREAD

**Issue by ORESoftware** [requirejs/requirejs#1709] opened 2018-01-11 17:51 UTC
I have this question on SO, if anyone can answer it, +20 points

https://stackoverflow.com/questions/48213040/injecting-module-into-amd-require-callback

**Comment by jrburke** [comment] 2018-01-11 19:49
Details here, just a collection of module-specific properties:

https://github.com/requirejs/requirejs/wiki/Differences-between-the-simplified-CommonJS-wrapper-and-standard-AMD-define#magic

Closing as a discussion ticket, but feel free to continue discussion here.

**Closed by jrburke** 2018-01-11 19:49 UTC

**Comment by ORESoftware** [comment] 2018-01-11 20:26
@jrburke right, but a require call, from the global space, isn't in a particular module.

e.g.

```js
// this === window
require(['foo', 'module'], function(foo, module){
  // I cannot think of a logical meaning of module here, what does it represent??
});
```

**Comment by daniel-white** [comment] 2018-01-11 20:34
My guess is that its a common path for both `require` and `define`.

**Comment by ORESoftware** [comment] 2018-01-12 00:32
like I said, my main concern would be if module passed to every require callback is unique or not, I am guessing not unique?

**Comment by jrburke** [comment] 2018-01-12 01:14
I believe it is [always a different object](https://github.com/requirejs/requirejs/blob/master/require.js#L590), but a warning: top level `require([])` calls should not rely on the `module` value being useful or intelligible. It was designed for use inside `define` calls, for commonjs matching purposes.

Top level `require([])` calls are not in a module, so it makes less sense to use it there.

**Comment by ORESoftware** [comment] 2018-01-12 01:29
right, that makes sense, so I definitely would like to bank on the fact that it's a different object. But what module actually represents in a top-level require call, is still unknown to me - what does it mean?

**Comment by chrisknoll** [comment] 2018-01-12 01:47
A top level require call does not define a module.  It makes sense to me that the module resolution in require is the same as the module Ids passed in the define() call, so you see some overlap here, but you'd have to look at the code to see how the literal 'module' id is handled (if at all).

When consuming a module, you don't have control over how the define is called, and it's up to the module being defined to use the 'module' appropraitely.  Conversely, you, as the requester of a module (via require()) _can_ control how the require is called. So unless you have some sort of purpose for passing in a module ID of 'module', why are you doing it?  Maybe that's the question that should have been answered: why would you pass in 'module' into a require() call when module is defined as the object context of the module being defined, but require() doesn't actually define a module?

**Comment by jrburke** [comment] 2018-01-12 01:48
Asking for `module` in a top level `require([])` call ideally would not be allowed. However because of implementation space concerns (back in the day most libraries were carefully scrutinized for file sizes), it is not explicitly disallowed. I was banking more on it not being relevant outside a module.

The `module` inside a `define` call is unique to that module, has information about that specific module ID and URL. A top level require call's `module` will have similar property keys, but the values are not meant to have specific meaning, may not make much sense.

**Comment by the1mills** [comment] 2018-01-12 02:35
Well I plan to make use of module instances injected into require callbacks, specifically as some form unique identifier.

I will run some tests to see where the uniqueness starts and ends, I am guessing at some point in nested requires, that injected module instances will no longer be unique.
