### ISSUE TITLE
  How should optimization if using multiple shim?

### ISSUE THREAD

**Issue by chalchis** [requirejs/requirejs#1417] opened 2015-09-07 15:40 UTC
as used in the example

https://github.com/requirejs/example-multipage-shim

or

https://github.com/requirejs/example-multipage

regards!!!!

**Comment by amenadiel** [comment] 2015-12-24 04:05
They are pretty much the same. The only difference is that one executes its main script inline whereas the other executes it through data-main attribute.

If you execute the main script by inlining it, then the optimizer won't alter it and you only need to optimize main1 and main2.

If you execute it through a separate script, then you want the optimizer to optimize said scripts (page1 and page2) and bundle their respective mains in the process.

**Comment by jrburke** [comment] 2016-03-14 04:32
Closing as a discussion issue, not a bug fix issue. Feel free to continue discussion here though.

**Closed by jrburke** 2016-03-14 04:32 UTC
