### ISSUE TITLE
Requiring a loaded module synchronously using require(modName as string) gives a not-loaded error

### ISSUE THREAD

**Issue by johnx7271** [requirejs/requirejs#1537] opened 2016-05-06 22:35 UTC
Requiring a loaded module synchronously, by using require(modName as string), gives a not-loaded error, if the require is made in a global scope, i.e. not inside any require or define call-back factory function.
The loaded module was loaded by a script tag before the require statement.
I am not sure if this is by design or a bug?

If it is by design, I feel this is not quite natural, and contradicts with common sense.

**Comment by amenadiel** [comment] 2016-05-07 00:35
Does it happen in node or are you requiring the module from the browser?

**Comment by johnx7271** [comment] 2016-05-07 01:05
browser.

**Comment by johnx7271** [comment] 2016-05-07 01:06
browser.

**Comment by ScottFreeCode** [comment] 2016-05-07 03:28
It's by design, I'm pretty sure. When a module is first referenced in a `define` dependency list or a `require` call, RequireJS inserts a script tag to get the browser to load it. But the browser won't run the script from the newly inserted tag until after it's done running the current script. There's no way it can pause during the call to `require` and wait to continue till the module loads -- except to put the code that should wait in a callback function to save for later, which is what the asynchronous form does.

Well, actually, I've (initially) glossed over a couple ways a loader could get around this, although they don't happen to apply here. One, it could load the module's code using AJAX/XMLHttpRequests (or similar technologies) instead of a script tag and parse it using an in-JavaScript JavaScript parser; but one of Asynchronous Module Definition's goals is to avoid having to use AJAX/XHR by default, so you'd have to know that your use-case allows for it and find an AMD loader specifically designed for it (or perhaps a plugin for a loader like RequireJS?)... Two, theoretically, I suppose the local require could load modules in browsers that provide the source code to functions through `toString()` if the loader scanned the callback function's source to look for calls to the local `require` and add the modules used in those calls to the dependency list for the outer `define` or `require` call that the callback belongs to; but I don't know if that's typically done or how difficult it is, and as far as I know there's no way to do it for top-level code outside a callback. (Hmm, now I want to come up with a test to find out if an AMD loader such as RequireJS supports using the local `require` to load new modules quasi-synchronously like that...) So, in the general case with AMD loaders, at least for the global `require`, the limitation I described initially still applies: the module can't load till the current script finishes running.

**Comment by jrburke** [comment] 2016-05-07 04:15
This was already touched on a bit, but the [sugared form for define](http://requirejs.org/docs/whyamd.html#sugar) does the Function toString scanning for `require(StringLiteral)` calls, loads and executes those dependencies, then executes that module body.

However a top level require that is just in an arbitrary script block or non-define()'d code, the loader cannot do that prescanning and loading, so it is not allowed in that case. For those cases, the async require([], function(){}) form is needed.

Closing as a discussion ticket, but feel free to continue discussion here.

**Closed by jrburke** 2016-05-07 04:15 UTC

**Comment by johnx7271** [comment] 2016-05-07 10:41
Ok, by design. Then could somebody please add it to doc, so others would not have raised this issue again?

Perhaps I need to clarify a little:  if the required module is already loaded by some other means (say by a previous script tag or anything), why would a require of it give a not-loaded error, just because the require happens outside a require/define closure? When a module is loaded, its name should have been somehow registered globally, so, later require can check on distionary and just return its export. How do you think?

**Comment by ScottFreeCode** [comment] 2016-05-10 02:01
I think it will return already loaded modules if you can get a script to run after a module is loaded, but I'm not sure there's any good way to do that... except maybe [shim config](http://requirejs.org/docs/api.html#config-shim)? As far as I'm aware, shim config is generally meant for scripts that don't make or use modules at all, though; I'm not sure how well it does with scripts that consume modules but don't use the AMD callback style (a quick test suggests it can be made to work as long as the shimmed modules aren't `require`ing relative paths, but I don't know if my test is thorough)...

Actually, speaking of non-AMD yet module-consuming code, are these Node.js/CommonJS modules? The optimizer should be able to convert and/or bundle those instead, if so.

**Comment by jrburke** [comment] 2016-05-10 16:12
To @johnx7271's question, calling define does not automatically execute the factory function to generate the imports. They are queued up internally and then claimed by a top level require call. This is important to match the non-build execution case and to support multiversion/multiple contexts.

I would not use shim config for this issue, this is just an issue about calling `require(StringLiteral)` before the module has been fully traced and defined by the module loader.
