### ISSUE TITLE
Syntax error when compiling minified script

### ISSUE THREAD

**Issue by 199911** [requirejs/requirejs#1583] opened 2016-09-05 04:19 UTC
/<my project directory>/node_modules/requirejs/bin/r.js:22358
        function addFile(file, fileUrl) {
        ^^^^^^^^
Loading "requirejs.js" tasks...ERROR
>> SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.

**Comment by jrburke** [comment] 2016-09-05 05:02
What are the steps to reproduce the error? I did the following in a project that already had a main.js file that used AMD modules. This was using node v6.2.1:

```
npm install requirejs
node_modules/.bin/r.js -o name="main" out="built.js"
```

and I did not see this error.

The addFile is part of the uglifyjs source. It may result in how I am combining the files, where uglifyjs specifies "use strict", so when I concatenate its source, it picks up the "use strict" for the addFile section.

So I may be able to adjust how the file is included in r.js, but let's figure out what steps were used that resulted in the error first.

**Comment by 199911** [comment] 2016-09-05 05:07
@jrburke 
I use grunt-contrib-requirejs to compile the require js
I have checked https://github.com/gruntjs/grunt-contrib-requirejs

They don't update the code and the dependency of require js is ["^2.2.0"](https://github.com/gruntjs/grunt-contrib-requirejs/blob/master/package.json#L19)

My configuration in grunt is 
```
requirejs: {
            options: {
                baseUrl: "<%= dir.theme %>/scripts",
                mainConfigFile: '<%= dir.theme %>/scripts/main.js',
                findNestedDependencies: true,
                optimize: "uglify2",
                generateSourceMaps: true,
                preserveLicenseComments: false,
                name: "main"
            },
            compile: {
                options: {
                    out: "<%= dir.theme %>/scripts/main-built.js",
                }
            }
        }
```

**Comment by jrburke** [comment] 2016-09-05 05:25
I put up this test repo to to try to reproduce the issue:

https://github.com/jrburke/rr

It works fine for me, but if you can modify that test repo to fail, feel free to open a pull request against that repo and then I can use it to figure out the issue.

**Comment by 199911** [comment] 2016-09-05 06:06
I got the error without modifying any thing, may be our environment is different
```
[root@f4be22cfe23e rr]# npm install
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
rr@1.0.0 /root/rr
├─┬ grunt@1.0.1
│ ├── coffee-script@1.10.0
│ ├─┬ dateformat@1.0.12
│ │ ├── get-stdin@4.0.1
│ │ └─┬ meow@3.7.0
│ │   ├─┬ camelcase-keys@2.1.0
│ │   │ └── camelcase@2.1.1
│ │   ├── decamelize@1.2.0
│ │   ├─┬ loud-rejection@1.6.0
│ │   │ ├─┬ currently-unhandled@0.4.1
│ │   │ │ └── array-find-index@1.0.1
│ │   │ └── signal-exit@3.0.0
│ │   ├── map-obj@1.0.1
│ │   ├── minimist@1.2.0
│ │   ├─┬ normalize-package-data@2.3.5
│ │   │ ├── hosted-git-info@2.1.5
│ │   │ ├─┬ is-builtin-module@1.0.0
│ │   │ │ └── builtin-modules@1.1.1
│ │   │ ├── semver@5.3.0
│ │   │ └─┬ validate-npm-package-license@3.0.1
│ │   │   ├─┬ spdx-correct@1.0.2
│ │   │   │ └── spdx-license-ids@1.2.2
│ │   │   └── spdx-expression-parse@1.0.3
│ │   ├── object-assign@4.1.0
│ │   ├─┬ read-pkg-up@1.0.1
│ │   │ ├─┬ find-up@1.1.2
│ │   │ │ ├── path-exists@2.1.0
│ │   │ │ └─┬ pinkie-promise@2.0.1
│ │   │ │   └── pinkie@2.0.4
│ │   │ └─┬ read-pkg@1.1.0
│ │   │   ├─┬ load-json-file@1.1.0
│ │   │   │ ├── graceful-fs@4.1.6
│ │   │   │ ├─┬ parse-json@2.2.0
│ │   │   │ │ └─┬ error-ex@1.3.0
│ │   │   │ │   └── is-arrayish@0.2.1
│ │   │   │ ├── pify@2.3.0
│ │   │   │ └─┬ strip-bom@2.0.0
│ │   │   │   └── is-utf8@0.2.1
│ │   │   └── path-type@1.1.0
│ │   ├─┬ redent@1.0.0
│ │   │ ├─┬ indent-string@2.1.0
│ │   │ │ └─┬ repeating@2.0.1
│ │   │ │   └─┬ is-finite@1.0.1
│ │   │ │     └── number-is-nan@1.0.0
│ │   │ └── strip-indent@1.0.1
│ │   └── trim-newlines@1.0.0
│ ├── eventemitter2@0.4.14
│ ├── exit@0.1.2
│ ├─┬ findup-sync@0.3.0
│ │ └── glob@5.0.15
│ ├─┬ glob@7.0.6
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.5
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.1
│ │ └── once@1.3.3
│ ├─┬ grunt-cli@1.2.0
│ │ └── resolve@1.1.7
│ ├── grunt-known-options@1.1.0
│ ├─┬ grunt-legacy-log@1.0.0
│ │ ├── colors@1.1.2
│ │ ├─┬ grunt-legacy-log-utils@1.0.0
│ │ │ ├─┬ chalk@1.1.3
│ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ └── ansi-regex@2.0.0
│ │ │ │ ├── strip-ansi@3.0.1
│ │ │ │ └── supports-color@2.0.0
│ │ │ └── lodash@4.3.0
│ │ ├── hooker@0.2.3
│ │ ├── lodash@3.10.1
│ │ └── underscore.string@3.2.3
│ ├─┬ grunt-legacy-util@1.0.0
│ │ ├── async@1.5.2
│ │ ├── getobject@0.1.0
│ │ ├── lodash@4.3.0
│ │ └─┬ which@1.2.10
│ │   └── isexe@1.1.2
│ ├── iconv-lite@0.4.13
│ ├─┬ js-yaml@3.5.5
│ │ ├─┬ argparse@1.0.7
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@2.7.3
│ ├─┬ minimatch@3.0.3
│ │ └─┬ brace-expansion@1.1.6
│ │   ├── balanced-match@0.4.2
│ │   └── concat-map@0.0.1
│ ├─┬ nopt@3.0.6
│ │ └── abbrev@1.0.9
│ ├── path-is-absolute@1.0.0
│ └── rimraf@2.2.8
└─┬ grunt-contrib-requirejs@1.0.0
  └── requirejs@2.3.0

npm WARN rr@1.0.0 No repository field.
[root@f4be22cfe23e rr]# grunt
>> Tasks directory "tasks" not found.

/root/rr/node_modules/requirejs/bin/r.js:22358
        function addFile(file, fileUrl) {
        ^^^^^^^^
Loading "requirejs.js" tasks...ERROR
>> SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by jrburke** [comment] 2016-09-05 06:21
What version of node is running the command?

**Comment by 199911** [comment] 2016-09-05 06:50
v0.10.42
There are no error when upgraded to v6.5.0

**Comment by falsyvalues** [comment] 2016-09-05 08:26
Doesn't work on node v0.12.2, in the other hand v4.1.2 works fine.

**Comment by frietz** [comment] 2016-09-05 08:45
Fails in v0.10.25
Upgraded node to v6.4.0 - works like a charm.

**Comment by csabakoncz** [comment] 2016-09-05 13:05
Fails with node v0.12.4

**Comment by it-ony** [comment] 2016-09-05 13:43
The error is caused by defining a function within the else block

```
if (options.spidermonkey) {
        toplevel = AST_Node.from_mozilla_ast(files);
    } else {
        function addFile(file, fileUrl) {
            // ...
        }
       // ...
    }
```

**Comment by jrburke** [comment] 2016-09-05 16:37
Looks like it is old 0.10 and 0.12 versions of node that report this problem, versions 4-6 report to be fine. I will track the final fix, which will go up today, in https://github.com/requirejs/r.js/pull/929. Closing this ticket out since the fix will happen in that other repo, under that other ticket.

**Closed by jrburke** 2016-09-05 16:37 UTC
