### ISSUE TITLE
define() dependencies sometimes is undefined

### ISSUE THREAD

**Issue by Deadly0** [requirejs/requirejs#1584] opened 2016-09-07 20:06 UTC
Sometimes when i refresh my app i got the error 
![Alt text](https://monosnap.com/file/0WG84A8lzz0if9YEclXVcx7cvkKgJP.png)

initial-loader.js
```
define(['angular', 'lodash'], function (angular, _) {
    console.log(_);
   // ...
});
```

main.js
```
require.config({
    waitSeconds: 30,
    baseUrl: 'assets/bower_components',
    paths: {
        'app': '../app',
        'templates': '../app/templates',
        'domReady': 'domReady/domReady',
        'angular': 'angular/angular',
        'angular-animate': 'angular-animate/angular-animate',
        'angular-aria': 'angular-aria/angular-aria',
        'angular-messages': 'angular-messages/angular-messages',
        'angular-resource': 'angular-resource/angular-resource',
        'angular-material': 'angular-material/angular-material',
        'angular-toastr': 'angular-toastr/dist/angular-toastr.tpls',
        'angular-ui-router': 'angular-ui-router/release/angular-ui-router',
        'jquery': 'jquery/dist/jquery',
        'jquery-mousewheel': 'jquery-mousewheel/jquery.mousewheel',
        'lodash': 'lodash/dist/lodash',
        'malihu-custom-scrollbar-plugin': 'malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min',
        'jquery-mark': 'mark.js/dist/jquery.mark',
        'requirejs': 'requirejs/require',
        'moment-duration-format': 'moment-duration-format/lib/moment-duration-format',
        'moment': 'moment/moment',
        'moment-timezone': 'moment-timezone/builds/moment-timezone-with-data-2010-2020',
        'angular-moment': 'angular-moment/angular-moment',
        'angular-drag-and-drop-lists': 'angular-drag-and-drop-lists/angular-drag-and-drop-lists',
        'google-maps-places': 'https://maps.googleapis.com/maps/api/js?libraries=places',
        'highcharts': 'highcharts/highcharts',
        'angularjs-slider': 'angularjs-slider/dist/rzslider',
        'angular-number-picker': 'angular-number-picker/dist/angular-number-picker',
        'angular-numeraljs': 'angular-numeraljs/dist/angular-numeraljs',
        'numeral': 'numeral/numeral',
        'v-accordion': 'v-accordion/dist/v-accordion', // unused now
        'md-pickers': 'mdPickers/dist/mdPickers',
        'xeditable': 'angular-xeditable/dist/js/xeditable',
        'ngScrollbars': 'ng-scrollbars/src/scrollbars',
        'rangy-core': 'rangy/rangy-core',
        'rangy-selectionsave': 'rangy/rangy-selectionsaverestore',
        'textAngular-sanitize': 'textAngular/dist/textAngular-sanitize',
        'textAngular': 'textAngular/dist/textAngular',
        'textAngularSetup': 'textAngular/dist/textAngularSetup',
        'scalyr': 'scalyr/scalyr',
        'ngCroppie': 'ngCroppie-alk-fork/unminified/ng-croppie', 
    },
    shim: {
        'angular': {
            deps: ['jquery'],
            exports: 'angular'
        },
        'jquery': {
            exports: 'jquery'
        },
        'angular-animate': {
            deps: ['angular']
        },
        'angular-messages': {
            deps: ['angular']
        },
        'angular-aria': {
            deps: ['angular']
        },
        'angular-resource': {
            deps: ['angular']
        },
        'angular-material': {
            deps: ['angular']
        },
        'angular-toastr': {
            deps: ['angular']
        },
        'malihu-custom-scrollbar-plugin': {
            deps: ['jquery']
        },
        'jquery-mark': {
            deps: ['jquery']
        },
        'angular-ui-router': {
            deps: ['angular']
        },
        'angular-drag-and-drop-lists': {
            deps: ['angular']
        },
        'angularjs-slider': {
            deps: ['angular']
        },
        'angular-number-picker': {
            deps: ['angular']
        },
        'angular-numeraljs': {
            deps: ['angular', 'numeral']
        },
        'md-pickers': {
            deps: ['angular', 'moment']
        },
        'xeditable': {
            deps: ['angular']
        },
        'v-accordion': {
            deps: ['angular', 'angular-animate']
        },
        'moment-duration-format': {
            deps: ['moment']
        },
        'moment-timezone': {
            deps: ['moment']
        },
        'angular-moment': {
            deps: ['angular', 'moment']
        },
        'ngScrollbars': {
            deps: ['jquery', 'angular', 'jquery-mousewheel', 'malihu-custom-scrollbar-plugin']
        },
        'textAngular': {
            deps: ['angular', 'textAngular-sanitize', 'textAngularSetup']
        },
        'textAngularSetup': {
            deps: ['angular']
        },
        'textAngular-sanitize': {
            deps: ['angular']
        },
        'rangy-selectionsave': {
            deps: ['rangy-core']
        },
        'scalyr': {
            deps: ['angular']
        },
        'ngCroppie': {
            deps: ['angular']
        },
    },

    deps: [
        'app/bootstrap',
    ]
});
```

If i add `console.log('lodash')` into lodash.js i got:
![Alt text](https://monosnap.com/file/oPyWULHii90A6xGTw1Zj2bkfqX5QNG.png)

Any ideas what is it and how to fix it?
Any suggestions is very appreciated, that bug is really annoying :(

P.S. `Lodash` is not the only problem, sometimes `angular` or `ui-router` or another module may be not loaded in dependencies.

**Comment by jrburke** [comment] 2016-09-08 02:36
If the error is in angular.js and it wants debounce off of underscore, then underscore should be mentioned as a dependency for angular in the shim config:

```javascript
    shim: {
        'angular': {
            deps: ['jquery', 'underscore'],
            exports: 'angular'
        },
```

Closing as a discussion ticket, but feel free to continue discussion here.

**Closed by jrburke** 2016-09-08 02:36 UTC

**Comment by Deadly0** [comment] 2016-09-08 09:13
@jrburke did you read my problem? I've defined my own module where lodash for some unknown for me reasons sometimes is undefined. 
```
define(['angular', 'lodash'], function (angular, _) {
    console.log(_); // console out put: undefined
   // ...
});
```

According the docs, callback function should be called when angular and lodash were defined but not before. Am i wrong?

**Comment by jrburke** [comment] 2016-09-08 14:11
If angular needed lodash too, since that module also references angular as a dependency and there is an error listed in the screenshot from angular.js about a debounce, which sounds like a lodash issue, then the angular dependency may fail/throw during loading which could cause havoc for other modules.

However, if that is not the cause and adding lodash to the angular shim dependencies does not fix it, perhaps a test case I can run will point to the issue. The only other thing off the top of my head: if you are running in a browser that has extensions on and running, turn off all the extensions to see if that has an effect. In the past there have been some extensions that mess with script loading.

**Comment by Deadly0** [comment] 2016-09-09 12:06
@jrburke angular is not depend on lodash
I've tried in incognito mode and it's fully reproduce the issue.

It's hard to publish a repo, it a big, non-open source project. I'm not sure i can catch the issue and reproduce it in a minimal project.

Do you have any suggestions how to debug this kind of issue and find the problem?
Thank you.

**Comment by jrburke** [comment] 2016-09-09 16:47
You've done some of that already, but expanding on it: I would confirm that the lodash is getting fetched in the developer tools network panel, maybe put some console.logs at the top and bottom of lodash to indicate when it starts loading, make sure it is fully executed before it is needed. 

If you put a breakpoint dependent on the module ID in the [check() function](https://github.com/requirejs/requirejs/blob/51d005fd962d57d5434a579f81f22bf51cdfb0a0/require.js#L840), or some console logs if you feel it is timing dependent, you could confirm if lodash when it is executed gets a proper export value, and that dependencies that need it are still waiting on it to complete.

I would also be sure that requirejs is up to date if it is an older version. Current release is 2.3.1.
