### ISSUE TITLE
Requirejs and Kendo UI 2016Q1

### ISSUE THREAD

**Issue by magnus-meridies** [requirejs/requirejs#1488] opened 2016-02-10 12:23 UTC
This combination seams not to work anymore since Telerik released Kendo UI Q1 2016. Telerik has changed their naming of the modules. This could be red in Telerik's forums: 

"The naming of the modules is necessary because the commercial files we distribute are assembled by multiple modules - we had to change thad in order to address the AMD loading of the bundle files in question. Previously, we had multiple cases of people hitting obscure bugs due to multiple modules being loaded from different bundles (like kendo.all + kendo.dropdownlist for example).  

Unfortunately, this brought the necessary change of the requireJS configuration - I agree with you that using the baseUrl for the kendo libraries is not a good solution, however, this seems to be the only way for requireJS to load such named modules. 

In case you have considered this an option, I would like to point out that other, modern module loaders like Webpack and SystemJS are much more flexible, and their configuration seems much better - check this and this help article."

How do others tackle this? Do we need to leave requirejs to get this to work? Is it possible to adjust anything in requirejs to get this to work?

**Comment by jrburke** [comment] 2016-02-10 14:09
I am unfamiliar with that toolkit or what part of the docs have that quote, any link suggestions I should use to try it out locally? In general, either an entry in [paths config](http://requirejs.org/docs/api.html#config-paths) or [map config](http://requirejs.org/docs/api.html#config-map) should be enough to get a set of modules to work, but not sure I understand yet how the module IDs and the file layouts are done in that project.

**Comment by magnus-meridies** [comment] 2016-02-12 07:10
The link: http://www.telerik.com/forums/issues-loading-latest-kendo-version-using-requirejs

**Comment by jbedard** [comment] 2016-02-12 07:53
I ran into this as well. I think kendo switched from using anonymous modules to named modules (at least in the individual js files, not sure about the kendo.all version). I had to switch all my references from `/path/to/kendo-ui/kendo.core.min` to just `kendo.core.min` (the module name they switched to) and use the [paths config](http://requirejs.org/docs/api.html#config-paths) to configure `kendo.core.min` to point to the correct path.  Same with other modules like `kendo.calendar.min` etc.

Kendo also added a dependency on `jquery` so that must also be defined as a path to jquery.js (or jQuery has to already be loaded) and this dependency no longer needs to be configured manually as a shim.

**Comment by jrburke** [comment] 2016-03-13 20:56
Closing as a discussion ticket, seems like this is something Telerik needs to sort out. One thought occurred to me is that if the problem is the named modules, and those named modules do not really have dependencies on the specific weird names in other modules, you could probably write a script that does a regexp replace for `/define\s*\(\s*['"][^'"]+['"]\s*,/define(/` to remove the names.

**Closed by jrburke** 2016-03-13 20:56 UTC
