### ISSUE TITLE
Optimizer creating an anonymous module

### ISSUE THREAD

**Issue by namel** [requirejs/requirejs#1347] opened 2015-05-12 13:44 UTC
This is a feature request...

Would be nice for the optimizer to have an option **makeAnonymous**.  Today
the optimizer always adds a module name to the primary define().  However this 
implies that the generated module is not trivially loadable (unless I missed something?).

Thanks!

**Comment by jrburke** [comment] 2015-05-13 16:33
I am not sure I am following the use case:

1) Is it a file that has a define in it, and you do not want to have an empty define() placed in it? If so then [skipModuleInsertion](https://github.com/jrburke/r.js/blob/6b57ce497e2761910b4c04824df6236936972dcd/build/example.build.js#L307) can help.

2) Or are other modules combined in with the module that is targeted for optimization, and you want all the modules to be named except for the one that was the target of the optimization (via the `name` build config)? If so, then talking more about why that is desired would be useful to know.

**Comment by ernestopye** [comment] 2016-06-30 21:23
Hi, just wanted to start by saying that your work is very much appreciated. require.js is a great tool!

I'm running into an issue that might be related because the proposed solution would solve my issue as well, although I do wonder if it's the right approach. My setup isn't conventional I'm assuming. But basically, I build my entire app into a single minified JS file:

app.min.js

Let's say that there's another file that app.min.js always loads:

external.loader.js (kept separate so it may be modified)

which in turn loads:

external.js (during development)
external.min.js (for production)

external.js works fine, as all modules are anonymous and it loads them on the fly. However external.min.js is r.js optimized and has named modules. If I try to require('path/to/external.min.js'), undefined is returned. I looked at the minified file, and the chunk from external.js receives a module name. So it looks something like this:

[a whole bunch of optimized js code from someotherdeps]
define('external',['require', 'someotherdeps'], function (require) {
   //...
return {};
});

The empty object is just for this example. The require() calls just return undefined though. However if I remove the name of this module and turn it into this:

[a whole bunch of optimized js code from someotherdeps]
define(['require', 'someotherdeps'], function (require) {
   //...
return {};
});

It works fine. It doesn't individually load the scripts for someotherdeps either, it works like I'd expect (this expectation may be incorrect). 

I figure what I'm doing isn't too common, but I wonder if you have any info on how to achieve something like this. Essentially dynamically loading an r.js optimized file from another r.js optimized file. It's very possible that I'm missing something obvious here, so apologies if I'm wasting your time.

**Comment by chrisknoll** [comment] 2016-07-01 00:39
I'll try to answer this one, but anyone else please correct me.

First and foremost: path to .js file is _not_ a module ID.  So require('path/to/external.min.js'), this call makes no sense because that is not a module ID.

Next: Although you don't specify a Module ID in an anonymous module, a module ID is in fact created for the anonymous module based on the runtime configuration of the requirejs.config.  All an optimizer does is load a root-level module (anonymously) and grab everything that is dependent and compile it into one big file, creates a module ID for every fetched module, and creates an internal map to the moduleIDs that were loaded to the root module such that by loading the optimized module, it actually 'virtually' loads all the dependents at once.  But all of those moduleIDs that were fetched at once have the same 'anonymousID' that would have been defined as if you loaded it on the fly.

So, to get what you want: it seems from inspecting the optimized external module, that the optimizer gave it the name 'external'. That's probably because you maybe made a path to it, or the root external.js file you had was found directly under your js root.  Now, to make it load your external, you just need to set up a path config like:

~~~~ javascript
path : {"external" : "path/to/external.min.js"}
~~~~~

Then, when your main app does a require('external', function() {}), it fetches the optimized code, all the dependent modules that were bundled into that one file are also registered with the amd loader (requirejs), such that any call made later that does a require('some module from external') it will find it from the single load of external.min.js.

So, play with the paths config and remember that the moduleID that would have loaded 'external.js' should be the same moduleID that you use when you want to load the optimized file, which is handled by defining a path config.

-Chris

**Comment by ernestopye** [comment] 2016-07-01 00:44
Hey thanks for the quick response. I'll play around with that. The extensions being there is a mistake. I was just writing something up based on our code, and left those in, oops. Am I wrong in using relative paths to load scripts with require? I don't always set up paths unless I need to. Is that not recommended?

**Comment by chrisknoll** [comment] 2016-07-01 00:59
Relative paths is fine, but remember, the relative path is a relative MODULE ID not a relative path to a file.  However, because paths to files are used to generate module IDs, it's extremely confusing at times to keep this separate in your mind. But, if you consider you have this filesystem:

external.js
external/
  /submoduleA.js
  /submoduleB.js

If you do soemthing in external JS such as:

~~~~javascript
// external.js
define([./external/submoduleA], function(subA) {} );
~~~~~
While it certainly LOOKS like you are fetching something from a relative path in a filesystem, what you are actally doing is loading a module that is relative to the module being loaded: 'external'. the define ./external/submoduleA resolves to 'external/external/submoduleA' which tries to load the module from a subdirectory from where  external is loaded from, and then a subdirectory called external, and then the file named submoduleA.js.

I know, it's confusing.  If the submoduleA was located as a peer file to external.js, you could do
~~~~javascript
// external.js
define([./submoduleA], function(subA) {} );
~~~~~

Which would fetch the submoduleA.js file fromt he same physical location as external.js, however, the moduleID this woudl be given is 'external/submoduleA'.

I know these moduleIDs->path translation is confusing, it screws me up a lot too, but once you get the handle on what the moduleID is going to be transformed into when it loads the physical module file, it gets a lot easier.

**Comment by ernestopye** [comment] 2016-07-01 01:01
Ahh I see what you mean. I don't think I knew that about paths relative to modules. Thanks for the great explanation. I'm going to spend more time with my config tomorrow to get this working. Thanks again.

**Comment by chrisknoll** [comment] 2016-07-01 01:06
Sure thing. One thing I do sometimes is i just put in relative modules in there (that might not point to anything real) just to see what require JS is going to try to load. Gets me to understand how a moduleID is transformed into a physical path.  Good luck and have fun!

**Comment by chrisknoll** [comment] 2016-07-01 01:09
Ha! I did it to myself:

Quote:
Relative paths is fine, but remember, the relative path is a relative MODULE ID not a relative path to a file. However, because paths to files are used to generate module IDs, it's extremely confusing at times to keep this separate in your mind. But, if you consider you have this filesystem:

What I should have said:
Relative paths is fine, but remember, the relative path is a relative MODULE ID not a relative path to a file. However, because **module IDs are used to generate paths to files**, it's extremely confusing at times to keep this separate in your mind. But, if you consider you have this filesystem:

**Comment by chrisknoll** [comment] 2017-08-21 15:26
@jrburke : I'd like to revisit this feature request.  I have a case where I'd like the optimized library to produce an anonymous module that is build based off of a package configuration.  Ie:

```javascript
requirejs.config({
	packages: [
		{
			name: "atlascharts",
			location: "../atlascharts",
			main: "main"
		}
	],
	paths: {
		"jquery": "https://code.jquery.com/jquery-1.11.2.min",
		"d3": "https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min",
		"d3_tip": "https://cdnjs.cloudflare.com/ajax/libs/d3-tip/0.7.1/d3-tip.min",
	}
});
```

Note that the d3 and d3_tip were anonymous modules that could take any path moduleID to find them, but jquery requires the module ID to be jquery.

My build command looks like this:

```
node node_modules/requirejs/bin/r.js -o build/build-dev.js
```

Note this above cmd is just a npm script that will invoke the r.js optimizer, passing it my configuration:

```
({
	mainConfigFile: 'config.js',
	normalizeDirDefines: "all",
	optimize:'none',
	name: 'atlascharts',
	out: '../dist/atlascharts.js'
});
```

So the optimizer is going to request 'atlascharts', bundle everything found in the package and put it under atlascharts/{submoduleId}, and not do any uglify (I leave that to a separate step using google closure compiler, which seems to work fine).

Here's the issue (same as the original poster):  the optimized module is not anonymous.  If you put anything except the below configuration value in the path in the require.js app, you'll get a error in define():

```
"atlascharts": "{path to optimized file}/atlascharts.min"
```

In this way, it works a lot like jquery:  you need to have your path configuration point to a specific moduleId or it will fail.

On one hand, I like pre-defining the module ID because this means that if it's going to be shared across applications (like jquery) you have to agree on a published moduleID.  On the other hand, anonymous modules are good in cases where you don't have that concern (or you can always use 'map' config to handle different ModuleIDs that need to route back to the same library.

So, I think I can understand why r.js needs some moduleId to be explicitly declared in the bundled module file (because by default, 1 module per file) but I'm wondering how to address the need for producing a anonymous module...

-Chris

**Comment by jrburke** [comment] 2017-08-22 06:34
Does `atlascharts` include other define()'d modules that you want to reference in other code, or are they considered "private" to the built structure?

If considered private, then an approach like [example-libglobal](https://github.com/requirejs/example-libglobal) could be taken. It is a bit dated, but there is enough in there that could give you an idea. If you did not want to include almond in the build, there are other [AMD API shims](https://github.com/requirejs/requirejs/wiki/AMD-API-Shims) that might be an option.

If you do want the other named modules in that bundle accessible and visible to the library that consumes `atlascharts`, then you could use then [onBuildWrite optimizer options](http://www.ericfeminella.com/blog/2012/03/24/preprocessing-modules-with-requirejs-optimizer/) to regexp out the module 'atlascharts' ID. 

However, this creates an awkward situation where if the consuming code for `atlascharts` wanted to use for example 'd3' and 'd3' is in that bundle, and the app require()'s it before `atlascharts` is loaded. That will require more config in the consuming app for it to work: [bundles config](http://requirejs.org/docs/api.html#config-bundles).

I am going to go ahead and close this ticket as a discussion ticket for now, but feel free to continue discussion here. I have been lax about closing out tickets that will likely not result in a code change. We can reopen if further discussion points to a change. I do not think it is likely in this case, but it is always reserved as an option.

**Closed by jrburke** 2017-08-22 06:34 UTC

**Comment by chrisknoll** [comment] 2017-08-22 17:11
Hi, @jrburke ,
  The atlascharts is a package, who's main.js module makes all the sub-modules 'reachable' by doing something like this:

```
require("atlascharts", function(chartLib) {
  var linePlot = new chartLib.line();
  // do work with the lineplot.
};
```
main.js looks like this:

```
define(function(require) {
	"use strict";
	
	var module = {
		version: "0.0.1"
	}
	
	var areachart = require("./areachart");
	var barchart = require("./barchart");
	var boxplot = require("./boxplot");
	var donut = require("./donut");
	var histogram = require("./histogram");
	var line = require("./line");
	var trellisline = require("./trellisline");
	var treemap = require("./treemap");
	var util = require("./util");
	
	module.areachart = areachart;
	module.barchart = barchart;
	module.boxplot = boxplot;
	module.donut = donut;
	module.histogram = histogram;
	module.line = line;
	module.trellisline = trellisline;
	module.util = util;
	
	return module;
	
});
```

Example of one of the modules that uses the d3 dependency (line.js):

```
define(["jquery", "d3", "d3_tip", "./util"], function($, d3, d3_tip, util) {
	"use strict";
  // module implementation
});
```

So, it's true that the consumer of this library needs to be using a module loader and configure it (or can bundle everything up using a packager). In our case, we just list the library dependencies in the project documentation ("jquery", "d3", and "d3_tip").  We don't package a loader with the library.

So to your comments:  

The inner modules could be considered private.  No need for an AMD shim, we tell people to use require.js or some other amd module loader which the'll need to configure to be able to resolve the module dependencies (and the atlascharts library itself). The only problem is that r.js makes the optimized module non-anonymous (you have to refer to atlascharts). But because this one .js file has mulitple modules in it, I understand that it may not be possible to have a non-anonymous module in it....so We may just have to live with it.

**Comment by jrburke** [comment] 2017-08-23 03:35
In that model, sounds like the modules will not truly be private, but if you are OK with that, then you can use the onBuildWrite approach to remove the module ID for the atlascharts define call, I think that should work.

**Comment by chrisknoll** [comment] 2017-08-23 03:50
I am fine with it, and I actually like the idea of being able to address sub-modules directly (like 'atlascharts/line') so you don't have to go through the outer module wrapper, and would even probably lend itself over to treeshaking as well.

The problem is that when you optimize, there's no way to get the bundle config out of it (I think I read that the only way to get the list of module IDs from a build if it's an entire project case, but in my case i'm building 1 module that happens to come from a package.  Really wish there was a way to do the module build and then specify a file to output the bundled modules into...or maybe hook into a optimizer callback that every time a module ID is identify it calls a callback and I could just track it that way.

**Comment by jrburke** [comment] 2017-08-23 03:56
If you wanted a lower level tool that just traces the module, then gives you back the contents of the modules and the trace so that you can programmatically combine them how you want, you might try [amodro-trace](https://github.com/amodrojs/amodro-trace).

**Comment by chrisknoll** [comment] 2017-08-23 04:02
Ok, thanks @jrburke .  Btw: just checked out your lib-global repo, and it pretty much mirrors exactly what I'm doing in my own library, except not bundling almond (so we need to tell library consumers how to configure their loader) and I'm referencing the module via a package configuration instead of your mode has a module filename named after the same folder that the sub modules are found....  And of course, you have the UMD wrapper which makes it nice to work inside a non-amd container....

Do you see an advantage of using a package config vs. a module.js file with a folder that follows the same name?  I feel the package approach is kinda elegant...if there's no concerns with using a package config vs. a entry module.js file, would you accept a PR on the libglobal repo that switches it up to use package config?  Or do you think it's to-ma-TO, to-MA-to with the different configuration approaches...?

**Comment by jrburke** [comment] 2017-08-23 05:27
The example-libglobal tries to be a plain example, there are lots of variations that are possible, including one that uses package config. If you end up using that repo as an example, if you fork it and update that fork with package config, I am open to linking to it in the main repo's readme as an example of a package-based config.

The super idealized version on module resolution for me is the `pkg.js + pkg/` folder approach, because if a package manager lays that out correctly, then the loader config is super small (just a baseUrl and maybe on paths entry for the app vs library code) and the default `baseUrl + moduleId + '.js'` resolution works.

Unfortunately, JS package managers have not pursued that route, so package config can be useful. I wish they allowed for writing out a pkg.js that points to loading the pkg/[main module ID from package.json] since that avoids a centralized config. 

So the choice of config is really down to idealized versions vs what is practical for a particular situation.
