### ISSUE TITLE
i found a bug about path resolving

### ISSUE THREAD

**Issue by zzzgit** [requirejs/requirejs#1528] opened 2016-04-15 05:48 UTC
#### project directory:
- index.html
- js
  - main.js
 - toolkit.js

#### index.html:
```html
<!DOCTYPE html>
<head>
	<title>Document</title>
	<script type="text/javascript" data-main="./js/main" src="./require.js"></script>
</head>
<body></body>
</html>
```
#### main.js:
```javascript
require.config({
	"baseUrl":"./js",
	"paths":{
		"short":"./"
	}
});
require(["short/toolkit"], function(toolkit) {
    console.log(toolkit.version);
});
```
#### toolkit.js:
```javascript
define("toolkit",function() {
    return {
        "version": "3.2"
    };
});
```
in this case,it will get an error:

> main.js:8 Uncaught TypeError: Cannot read property 'toolkit' of undefined

why?
now i modify the file `toolkit.js` to this:
```javascript
define({
        "version": "3.2"
});
```
then it works 
why why why?

**Comment by radishj** [comment] 2016-04-15 06:19
Try this：
```
require.config({
    "baseUrl":"./js",
    "paths":{
        "short":"./"
    }
});
require(["short/toolkit"], function(toolkit) {
    console.log(toolkit().version);
});
```

**Comment by jrburke** [comment] 2016-04-15 14:28
The issue is that toolkit.js named itself "toolkit", but this name does not match the name your other code used to refer to it, "short/toolkit".

It is best to use anonymous modules for the modules when in source form. That way its name will be determined by how the other modules refer to it. 

A module is anonymous if you leave off the string ID as the first argument.Your change to just use the object literal passed to define() so that is why it works. If you wanted something closer to your original code, this will also work:

```javascript
define(function() {
    return {
        "version": "3.2"
    };
});
```

Closing as a discussion ticket, but feel free to continue discussion here.

**Closed by jrburke** 2016-04-15 14:28 UTC
