### ISSUE TITLE
wrong relative path resolution

### ISSUE THREAD

**Issue by sgratzl** [requirejs/requirejs#1395] opened 2015-07-24 15:29 UTC
I have the following directory structure: 
```
a/afile.js -> depends on ../d/dfile
a/b/abfile.js -> depends on ../../d/file
d/dfile.js
```

However, the different dependencies to the same file are resolved to different module(ids), resulting in executing the module twice. 

I assume the bug is in `trimDots` method.
test case: 
Input: `b/../../d/dfile`
expected: `../d/dfile`
result: `b/../../d/dfile`

require.js line 247: `if (i === 0 || (i === 1 && ary[2] === '..') || ary[i - 1] === '..') {` 

I don't get the `ary[2] === '..'` check

Any ideas?

**Comment by Samlv9** [comment] 2015-07-25 01:06
where is your `main` module?

**Comment by Samlv9** [comment] 2015-07-25 01:29
i have test your code with a `main` module, and it does not get error.
![1](https://cloud.githubusercontent.com/assets/6926770/8887329/83b2db2a-32af-11e5-88e4-217694abcfce.png)
![2](https://cloud.githubusercontent.com/assets/6926770/8887330/86ff3986-32af-11e5-8759-e9c01188aaab.png)
![3](https://cloud.githubusercontent.com/assets/6926770/8887332/88e455a6-32af-11e5-8570-9bdea90476fe.png)
![4](https://cloud.githubusercontent.com/assets/6926770/8887333/8a985ad2-32af-11e5-9acd-03fcbf5e80b5.png)
![5](https://cloud.githubusercontent.com/assets/6926770/8887335/8c3caa46-32af-11e5-8bcb-60f7aa851e43.png)
![6](https://cloud.githubusercontent.com/assets/6926770/8887336/8da158d2-32af-11e5-8364-182f032a74d7.png)
![7](https://cloud.githubusercontent.com/assets/6926770/8887338/8f1b0f5a-32af-11e5-9c75-7f8257606c5a.png)

**Comment by sgratzl** [comment] 2015-07-25 12:28
the situation is this: I have a couple of independent application under a different suburl sharing some code and modules. 

e.g. 
```
app1/index.html
app2/index.html
lib1/a.js
lib1/sub/b.js
lib2/c.js
```
the both index.html require the require.js library. Instead of having a dedicated main module, I'm using the deps config entry in the require.js config. This allows me that an application requires a single file, which will be generated on the server.Anyhow, I can reproduce this situation. I forked the bower version and just removed the one clause. Now, it is working as expected. 

thanks

**Comment by toarnold** [comment] 2016-04-19 08:41
I can reproduce the issue.
It seems to be a problem adressing a file above the baseUrl.
I have the following solution structure:

index.html <-- baseUrl: 'Scripts'
Scripts/file.js
testing/index.html <-- baseUrl: '.'
testing/atest.js
testing/b/btest.js

atest.js requires '../Scripts/file.js
btest.js requires '.../../Scripts/file.js

If I open 'testing/index.html' both test files get different instances from file.js and the browser has loaded file.js twice

Tested with RequireJS 2.2.0. Here is my sample structure: [Sample.zip](https://github.com/requirejs/requirejs/files/225504/Sample.zip)

**Comment by chrisknoll** [comment] 2016-04-19 17:22
Module IDs != file paths. If you are requiring ../Scripts becuase it's up a folder from the location of the module, then you're confusing moduleIDs with directories.  baseURL is supposd to be the root, but it looks like you have 'siblings' to your base that are also bases.  Try to make a root as your baseURL and the other stuff goes beneath that.

**Comment by jrburke** [comment] 2016-04-20 04:31
Correct, module IDs are in their own ID space. Asking for something outside that module space (via '../something' will lead to bad results. It is unfortunately a bit confusing since plain URLs are allowed as a module ID as a convenience, but they do not operate like module IDs for the purpose of config and for relative ID path segment resolution. It is best to stick withe module IDs for dependencies.

In addition to adjusting the baseUrl, the other option is to use [paths config](http://requirejs.org/docs/api.html#config-paths) to set up a root for a module prefix that is outside the baseUrl. In the latest example, it looks like setting up a paths config for 'file' would be enough:

```javascript
requirejs.config({
  baseUrl: '.',
  'file': '../Scripts/file'
});
```

Then both atest.js and btest.js can depend on 'file'.

Closing as a discussion ticket, but feel free to continue discussion here.

**Closed by jrburke** 2016-04-20 04:31 UTC
